version: '3.8' 

services:   
  db:
    container_name: postgresDB
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: fastAPIuser
      POSTGRES_PASSWORD: fastAPI
      POSTGRES_DB: CloudDB
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./scripts/vgsales.csv:/tmp/vgsales.csv
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      cloudNet:
        ipv4_address: 192.168.0.2

  backend:
    container_name: CloudBackend
    build: 
      dockerfile: Dockerfile
      context: ../backend
    ports:
      - 8000:8000
    environment:
      DATABASE_IP: 192.168.0.2
      FRONTEND_IP: 192.168.0.4
    depends_on:
      - db
    networks:
      cloudNet:
        ipv4_address: 192.168.0.3

  frontend:
    container_name: CloudFrontend
    stdin_open: true
    build: 
      dockerfile: Dockerfile.production
      context: ../frontend
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      VITE_BASE_URL: http://192.168.0.3/games
    networks:
      cloudNet:
        ipv4_address: 192.168.0.4
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      cloudNet:
        ipv4_address: 192.168.0.5

volumes:
  postgres:

networks:
  cloudNet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/28