FROM node:18.14.2 as dist

WORKDIR /app

COPY package.json ./

COPY ./ ./

RUN npm install

RUN npm run build


FROM nginx:1.22.0-alpine

COPY --from=dist /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]